import 'package:flutter/material.dart';
import 'package:quiz_flutter/screen/change_language/change_language.dart';
import 'package:quiz_flutter/screen/common_info_screen/common_info_screen.dart';
import 'package:quiz_flutter/screen/course_detail/course_detail.dart';
import 'package:quiz_flutter/screen/course_list_screen/course_list_screen.dart';
import 'package:quiz_flutter/screen/course_video_screen/course_video_screen.dart';
import 'package:quiz_flutter/screen/favorite_screen/favorite_screen.dart';
import 'package:quiz_flutter/screen/forgot_password_screen/forgot_password.dart';
import 'package:quiz_flutter/screen/home_screen/home_screen.dart';
import 'package:quiz_flutter/screen/main_screen.dart/main_screen.dart';
import 'package:quiz_flutter/screen/profile_screen/profile_screen.dart';
import 'package:quiz_flutter/screen/quiz_play_screen/quiz_play_screen.dart';
import 'package:quiz_flutter/screen/quiz_screen/quiz_screen.dart';
import 'package:quiz_flutter/screen/setting_screen/setting_screen.dart';
import 'package:quiz_flutter/screen/sign_in_screen/sign_in.dart';
import 'package:quiz_flutter/screen/sign_up_screen/sign_up.dart';
import 'package:quiz_flutter/screen/splash_screen/splash.dart';

part 'manager_routes.dart';
